// ── Grammar Quiz Question Bank ────────────────────────────────
// Each question: { question, answers[], correct (index), explanation }
// explanation shows for both correct AND incorrect answers in quiz-engine

function getGrammarQuestions(level) {
  switch (level) {
    case 'reception': return grmReception();
    case 'year1':     return grmYear1();
    case 'year2':     return grmYear2();
    case 'year3':     return grmYear3();
    case 'year4':     return grmYear4();
    case 'year5':     return grmYear5();
    case 'year6':     return grmYear6();
    default:          return grmYear1();
  }
}

function grmQ(question, answers, correct, explanation, emoji) {
  return { question, answers, correct, explanation, emoji: emoji || null };
}

// ── Reception (Age 4–5) ─────────────────────────────────────
function grmReception() {
  return [
    grmQ('Which sentence is written correctly?',
      ['the dog ran fast.', 'The dog ran fast.', 'the Dog ran fast.', 'the dog Ran fast.'],
      1, 'Every sentence starts with a big capital letter! 🔠', '🐶'),
    grmQ('What do we put at the END of a sentence?',
      ['A comma (,)', 'A full stop (.)', 'A question mark (?)', 'Nothing'],
      1, 'A full stop (.) tells us the sentence has finished!'),
    grmQ('Which word should have a capital letter?',
      ['run', 'big', 'emma', 'fast'],
      2, 'People\'s names always start with a capital letter! Emma is a name. 👧'),
    grmQ('Which is a complete sentence?',
      ['The big', 'Running fast', 'The cat sat on the mat.', 'A red'],
      2, 'A complete sentence makes sense on its own and has a full stop! ✅'),
    grmQ('Which sentence is a question?',
      ['The bird can fly.', 'I like cake.', 'Can birds fly?', 'Birds have wings.'],
      2, 'Questions ask something and end with a question mark (?). 🤔'),
    grmQ('Which word is a NAME?',
      ['jump', 'blue', 'happy', 'Liam'],
      3, 'Names of people and places start with a capital letter! 👦'),
    grmQ('Where does a capital letter go?',
      ['In the middle of a sentence', 'At the start of a sentence', 'At the end of a sentence', 'On every word'],
      1, 'Capital letters go at the very START of every sentence! ✍️'),
    grmQ('Which sentence ends correctly?',
      ['I like ice cream?', 'I like ice cream!', 'I like ice cream,', 'I like ice cream'],
      1, '"I like ice cream!" uses an exclamation mark to show excitement! 🍦'),
    grmQ('How many sentences are in this: "The cat sat. The dog ran."?',
      ['One', 'Two', 'Three', 'Four'],
      1, 'Each full stop ends one sentence. Two full stops = two sentences! ✌️'),
    grmQ('Which word is an ANIMAL?',
      ['run', 'cat', 'blue', 'happy'],
      1, 'A cat is a naming word (noun). Nouns are names of things, people, or animals! 🐱'),
    grmQ('Which is the correct way to start? "___ am happy."',
      ['i', 'I', 'ı', 'ii'],
      1, 'The word "I" is always written as a big capital letter — all on its own! 👆'),
    grmQ('Which sentence has a QUESTION MARK?',
      ['I love you.', 'Stop!', 'What is your name?', 'We went to school.'],
      2, 'Question marks (?) go at the end of questions — things we want to know! 🤔'),
    grmQ('Which word is an ACTION word (verb)?',
      ['cat', 'red', 'jump', 'happy'],
      2, '"Jump" is an action word! We use verbs to describe what someone is doing. 🏃'),
    grmQ('Which sentence tells us something EXCITING?',
      ['The sun is out.', 'We went home.', 'Wow, I won!', 'The bag is big.'],
      2, 'Exclamation marks (!) show excitement or surprise! 🎉'),
    grmQ('Which of these is a WORD?',
      ['xqzp', 'cat', '1234', '???'],
      1, 'Words are groups of letters that have meaning. "Cat" is a real word! 🐱'),
  ];
}

// ── Year 1 (Age 5–6) ────────────────────────────────────────
function grmYear1() {
  return [
    grmQ('Which sentence uses capital letters correctly?',
      ['my name is jack.', 'My name is Jack.', 'My Name Is Jack.', 'my name is Jack.'],
      1, 'Capital letters start sentences AND names of people. Jack is a name! 👦'),
    grmQ('What punctuation ends a question?',
      ['Full stop (.)', 'Comma (,)', 'Question mark (?)', 'Exclamation mark (!)'],
      2, 'Questions always end with a question mark (?). Think: "What? Where? When? Why?" 🤔'),
    grmQ('Which word is a NOUN (naming word)?',
      ['run', 'happy', 'table', 'quickly'],
      2, '"Table" is a noun — it\'s the name of a thing. Nouns name people, places, and things! 🪑'),
    grmQ('Which word is a VERB (action word)?',
      ['big', 'green', 'swim', 'sad'],
      2, '"Swim" is a verb! Verbs describe actions or what someone does. 🏊'),
    grmQ('Which joining word (conjunction) fits? "I like cats ___ dogs."',
      ['but', 'because', 'and', 'so'],
      2, '"And" joins two things together when they are both true. I like cats AND dogs! 🐱🐶'),
    grmQ('Which sentence needs an exclamation mark?',
      ['I had lunch.', 'The sky is blue.', 'Watch out for the bee', 'She went home.'],
      2, '"Watch out!" shows urgency or excitement — it needs an exclamation mark (!)! 🐝'),
    grmQ('Which word is an ADJECTIVE (describing word)?',
      ['run', 'fluffy', 'eat', 'quickly'],
      1, '"Fluffy" describes what something is like. Adjectives describe nouns! 🐑'),
    grmQ('Which sentence is correct?',
      ['london is in england.', 'London is in England.', 'london is in England.', 'London is in england.'],
      1, 'Names of places like London and England always start with capital letters! 🏙️'),
    grmQ('Choose the correct sentence:',
      ['can you help me', 'Can you help me.', 'Can you help me?', 'can You help me?'],
      2, 'A question starts with a capital letter and ends with a question mark (?). 🙋'),
    grmQ('Which word joins two ideas? "I was tired ___ I kept going."',
      ['and', 'but', 'or', 'not'],
      1, '"But" connects two opposite ideas. I was tired BUT I kept going! 💪'),
    grmQ('Which punctuation mark shows a LIST? "I need milk, eggs ___ bread."',
      ['Full stops', 'Question marks', 'Commas', 'Exclamation marks'],
      2, 'Commas (,) separate items in a list. Milk, eggs AND bread! 🛒'),
    grmQ('Which word is a PLACE (proper noun)?',
      ['park', 'france', 'France', 'city'],
      2, 'France is the name of a country — proper nouns (names of places) need capital letters! 🗺️'),
    grmQ('What is a SENTENCE?',
      ['Just any word', 'A word that ends in a full stop', 'A group of words that makes complete sense', 'Two letters joined together'],
      2, 'A sentence is a group of words that makes complete sense by itself! ✅'),
    grmQ('Which word shows TIME? "___ we got home, we had dinner."',
      ['Because', 'And', 'When', 'Or'],
      2, '"When" is a conjunction that tells us about time — it links two ideas together! ⏰'),
    grmQ('Which sentence is CORRECT punctuation?',
      ['Wow that is amazing', 'Wow, that is amazing!', 'Wow. that is amazing!', 'wow, that is amazing!'],
      1, '"Wow, that is amazing!" starts with a capital, has a comma after "Wow", and ends with ! 🎉'),
  ];
}

// ── Year 2 (Age 6–7) ────────────────────────────────────────
function grmYear2() {
  return [
    grmQ('What does an APOSTROPHE do in "I can\'t wait"?',
      ['Shows possession', 'Shows a list', 'Shows a missing letter (contraction)', 'Ends a sentence'],
      2, '"Can\'t" is short for "cannot". The apostrophe replaces the missing letter "no"! 📝'),
    grmQ('Which sentence uses "because" correctly?',
      ['I was late because I missed the bus.', 'Because I was late.', 'I was late, because.', 'Because late I was.'],
      0, '"Because" gives the reason for something and connects two clauses together! 🚌'),
    grmQ('Which word is an ADJECTIVE in this sentence? "The big, red ball rolled away."',
      ['ball', 'rolled', 'big', 'away'],
      2, '"Big" and "red" are adjectives — they describe what the ball looks like! 🔴'),
    grmQ('Which contraction is correct for "do not"?',
      ["don't", "do'nt", "dont'", "d'ont"],
      0, '"Don\'t" — the apostrophe replaces the "o" in "not". Do + not = don\'t! ✂️'),
    grmQ('Which sentence is punctuated correctly?',
      ['She asked, "Can I come?"', 'She asked "Can I come?"', 'She asked can i come?', 'she asked, can I come.'],
      0, 'Speech is wrapped in inverted commas (" "). A capital starts and a comma follows the speech tag! 💬'),
    grmQ('What is the PLURAL of "child"?',
      ['childs', 'childes', 'children', 'child\'s'],
      2, '"Children" is an irregular plural — it doesn\'t just add an "s". Learn it by heart! 👫'),
    grmQ('Which word is a VERB in "The rabbit hopped into the garden."?',
      ['rabbit', 'garden', 'hopped', 'into'],
      2, '"Hopped" is the verb — it tells us what the rabbit DID! 🐰'),
    grmQ('Which sentence is in the PAST TENSE?',
      ['She runs to school.', 'She is running to school.', 'She ran to school.', 'She will run to school.'],
      2, '"Ran" is past tense — it tells us the action has already happened. 🏃‍♀️'),
    grmQ('Which joining word shows CONTRAST? "I wanted cake ___ there was none left."',
      ['and', 'because', 'but', 'so'],
      2, '"But" shows a contrast between two ideas — you wanted cake BUT there was none! 🎂'),
    grmQ('Which sentence uses commas correctly in a list?',
      ['I bought apples oranges and bananas.', 'I bought apples, oranges and bananas.', 'I bought, apples, oranges, and, bananas.', 'I bought apples; oranges; and bananas.'],
      1, 'Commas separate items in a list. The last item uses "and" instead of a comma! 🍎🍊🍌'),
    grmQ('What does the apostrophe mean in "the cat\'s tail"?',
      ['The cat is missing', 'The tail belongs to the cat', 'Two cats', 'The cat was here'],
      1, 'An apostrophe + s shows possession — the tail BELONGS TO the cat! 🐱'),
    grmQ('Which is the CORRECT contraction for "she will"?',
      ["she'will", "sh'ell", "she'll", "shel'l"],
      2, '"She\'ll" — the apostrophe replaces "wi" in "will". She + will = she\'ll! 👩'),
    grmQ('Which sentence is in the PRESENT TENSE?',
      ['They played football.', 'They will play football.', 'They play football.', 'They had played football.'],
      2, '"Play" (present tense) tells us what is happening NOW or regularly! ⚽'),
    grmQ('Which word BEST completes: "She was ___ she had won the prize."?',
      ['sad because', 'delighted because', 'bored because', 'scared because'],
      1, '"Delighted because" makes the most sense — winning a prize makes you happy! 🏆'),
    grmQ('Which punctuation ends an EXCLAMATORY sentence?',
      ['Full stop (.)', 'Comma (,)', 'Question mark (?)', 'Exclamation mark (!)'],
      3, 'Exclamation marks (!) end sentences that show strong feelings or commands! 😮'),
  ];
}

// ── Year 3 (Age 7–8) ────────────────────────────────────────
function grmYear3() {
  return [
    grmQ('Which sentence uses a FRONTED ADVERBIAL correctly?',
      ['After lunch, we played outside.', 'We played outside, after lunch.', 'After lunch we played outside.', 'We, after lunch, played outside.'],
      0, 'A fronted adverbial starts the sentence and is followed by a COMMA. "After lunch," sets the scene! ⏰'),
    grmQ('Which word is a PREPOSITION in "The cat sat under the table"?',
      ['cat', 'sat', 'under', 'table'],
      2, '"Under" is a preposition — it shows WHERE the cat was in relation to the table! 🐱'),
    grmQ('Which conjunction shows TIME?',
      ['but', 'because', 'while', 'or'],
      2, '"While" is a time conjunction — "I ate while watching TV." It says two things happen at the same time! ⏱️'),
    grmQ('Which sentence uses INVERTED COMMAS correctly?',
      ['"I love books", said Maya.', '"I love books," said Maya.', 'I love books, said Maya.', '"I love books" said Maya.'],
      1, 'A comma comes INSIDE the closing inverted comma before the speech tag. "..," said Maya. 📖'),
    grmQ('Which word is an ADVERB in "She ran quickly to the door"?',
      ['ran', 'quickly', 'door', 'she'],
      1, '"Quickly" is an adverb — it describes HOW she ran. Adverbs often end in -ly! 🚀'),
    grmQ('Which sentence has a SUBORDINATE CLAUSE?',
      ['The dog barked.', 'The dog barked loudly.', 'Although it was raining, we went out.', 'We went out and had fun.'],
      2, '"Although it was raining" is a subordinate clause — it cannot stand alone but adds meaning! 🌧️'),
    grmQ('Which is the correct POSSESSIVE apostrophe for multiple dogs?',
      ["the dog's collar", "the dogs' collars", "the dogs collar", "the dogs's collars"],
      1, 'For plurals ending in "s", the apostrophe goes AFTER the s: dogs\' collars! 🐕'),
    grmQ('What does the prefix "un-" mean in "unhappy"?',
      ['Very happy', 'Not happy', 'A little happy', 'Always happy'],
      1, 'The prefix "un-" means NOT. Un + happy = not happy! 😔'),
    grmQ('Which sentence has a CONJUNCTION that shows REASON?',
      ['I ran because I was late.', 'I ran and I was late.', 'I ran while I was late.', 'I ran but I was late.'],
      0, '"Because" gives the reason — it explains WHY you ran. I ran BECAUSE I was late! 🏃'),
    grmQ('Which word is an ABSTRACT NOUN?',
      ['table', 'dog', 'happiness', 'London'],
      2, '"Happiness" is an abstract noun — it\'s something you feel, not touch or see! 😊'),
    grmQ('Which sentence uses the PRESENT PERFECT tense?',
      ['She runs every day.', 'She ran yesterday.', 'She has run three miles.', 'She will run tomorrow.'],
      2, '"Has run" is present perfect — the action happened recently and affects the present! 🏅'),
    grmQ('Which uses DIRECT SPEECH correctly?',
      ['Tom said he was hungry.', '"I am hungry," said Tom.', '"I am hungry" said Tom.', '"i am hungry," said Tom.'],
      1, 'Direct speech: inverted commas, comma inside, capital letter starts the speech. ✅'),
    grmQ('Which word is a NOUN PHRASE modifier in "the enormous grey elephant"?',
      ['elephant', 'enormous grey', 'the', 'enormous'],
      1, '"Enormous grey" are adjectives that modify (describe) the noun "elephant" as a phrase! 🐘'),
    grmQ('Which is a COMPOUND SENTENCE?',
      ['The bird flew.', 'The bird flew swiftly over the trees.', 'The bird flew and the cat watched.', 'Because the bird flew.'],
      2, 'A compound sentence joins two independent clauses with a conjunction like "and"! 🐦🐱'),
    grmQ('Which suffix changes "hope" into an adjective?',
      ['-ing', '-ful', '-ed', '-er'],
      1, '"Hopeful" — the suffix "-ful" turns the noun/verb "hope" into an adjective meaning full of hope! 🌟'),
  ];
}

// ── Year 4 (Age 8–9) ────────────────────────────────────────
function grmYear4() {
  return [
    grmQ('Which sentence uses a RELATIVE CLAUSE correctly?',
      ['The girl, which was clever, won the prize.', 'The girl who was clever won the prize.', 'The girl that she was clever won the prize.', 'The girl clever won the prize.'],
      1, '"Who" introduces relative clauses for people. "The girl who was clever" tells us more about the girl! 🏆'),
    grmQ('Which sentence uses BRACKETS correctly?',
      ['The Amazon (the world\'s largest river) flows through Brazil.', 'The Amazon, the world\'s largest river flows through Brazil.', 'The Amazon the world\'s largest river flows through Brazil.', '(The Amazon) the world\'s largest river flows through Brazil.'],
      0, 'Brackets ( ) add extra information that could be removed without changing the main meaning! 🌊'),
    grmQ('Which word is a PRONOUN in "She gave him the book"?',
      ['gave', 'book', 'She', 'the'],
      2, '"She" and "him" are pronouns — they replace nouns (names) to avoid repetition! 📚'),
    grmQ('Which sentence uses a FRONTED ADVERBIAL correctly?',
      ['Slowly, the tortoise crossed the line.', 'The tortoise, slowly, crossed the line.', 'The tortoise crossed, slowly, the line.', 'The tortoise crossed the line slowly,'],
      0, '"Slowly," fronted adverbial + comma, then the main clause. Sets the manner of the action! 🐢'),
    grmQ('Which sentence is in the PASSIVE VOICE?',
      ['The chef cooked the meal.', 'The meal was cooked by the chef.', 'The chef is cooking.', 'The meal cooked itself.'],
      1, 'Passive voice: the object becomes the subject. "The meal was cooked" — the meal is the focus! 🍽️'),
    grmQ('Which correctly uses INVERTED COMMAS for speech?',
      ['"Run!" shouted the coach.', 'Run! shouted the coach.', '"Run" shouted the coach!', '"Run!" Shouted the coach.'],
      0, 'After "Run!" the speech mark closes, then lowercase "shouted". ✅'),
    grmQ('What is the function of a COLON (:)?',
      ['To join two sentences together', 'To introduce a list or explanation', 'To show possession', 'To replace a full stop'],
      1, 'A colon (:) introduces a list or explanation: it says "here comes more detail"! 📋'),
    grmQ('Which word is a MODAL VERB?',
      ['run', 'could', 'happy', 'table'],
      1, '"Could" is a modal verb — it shows possibility or ability. Could, would, should, might, can! 💭'),
    grmQ('Which sentence uses DASHES correctly for parenthesis?',
      ['The match — which was brilliant — ended in a draw.', 'The match — which was brilliant ended in a draw.', 'The match which was brilliant — ended in a draw.', 'The match — which was brilliant,— ended in a draw.'],
      0, 'Dashes come in pairs to add extra information — just like brackets! ⚽'),
    grmQ('Which sentence contains a SUBORDINATE CLAUSE introduced by "although"?',
      ['Although she tried hard.', 'Although she tried hard, she did not win.', 'She tried hard, although.', 'She tried, hard although.'],
      1, '"Although she tried hard" is subordinate — it cannot stand alone. It depends on the main clause! 💪'),
    grmQ('What does a SEMI-COLON (;) do?',
      ['Ends a sentence', 'Links two related independent clauses without a conjunction', 'Shows possession', 'Introduces a list after a colon'],
      1, 'A semi-colon links two closely related sentences: "I studied hard; I passed the test." 📝'),
    grmQ('Which is a COMPLEX SENTENCE?',
      ['The cat sat.', 'The cat sat and slept.', 'When it rained, the cat stayed inside.', 'The cat: sat and slept.'],
      2, 'A complex sentence has a main clause + a subordinate clause. "When it rained" is subordinate! 🌧️🐱'),
    grmQ('Which sentence uses the PERFECT TENSE correctly?',
      ['She eat all her dinner.', 'She has eaten all her dinner.', 'She eating all her dinner.', 'She eats all her dinner yesterday.'],
      1, '"Has eaten" is the present perfect — formed with "have/has" + past participle. 🍴'),
    grmQ('Which is a POSSESSIVE PRONOUN?',
      ['he', 'them', 'theirs', 'who'],
      2, '"Theirs" is a possessive pronoun — it shows ownership without naming the noun. Mine, yours, his, hers, ours, theirs! 🔑'),
    grmQ('Which correctly uses a COMMA after a fronted adverbial?',
      ['After the storm the rainbow appeared.', 'After the storm, the rainbow appeared.', 'After the storm; the rainbow appeared.', 'After the storm: the rainbow appeared.'],
      1, 'A fronted adverbial MUST be followed by a comma before the main clause. ✅🌈'),
  ];
}

// ── Year 5 (Age 9–10) ───────────────────────────────────────
function grmYear5() {
  return [
    grmQ('Which sentence uses a RELATIVE CLAUSE with "whose"?',
      ['The student, who won, was happy.', 'The student whose work was best won the prize.', 'The student which won was happy.', 'The student won, who was happy.'],
      1, '"Whose" introduces relative clauses showing belonging — "whose work" refers to the student\'s work! 🏆'),
    grmQ('Which sentence is in the PASSIVE VOICE?',
      ['Scientists discovered a new planet.', 'A new planet was discovered by scientists.', 'Scientists are discovering planets.', 'A planet scientists discovered.'],
      1, 'Passive: object (planet) becomes subject, and the agent (scientists) follows "by". 🔭'),
    grmQ('Which sentence uses a MODAL VERB to show CERTAINTY?',
      ['She might come.', 'She must come.', 'She could come.', 'She may come.'],
      1, '"Must" shows near certainty. Might, could, may show possibility; must shows you\'re sure! ✅'),
    grmQ('Which correctly uses PARENTHESIS with commas?',
      ['My teacher, who is very kind gave me extra help.', 'My teacher, who is very kind, gave me extra help.', 'My teacher who, is very kind, gave me extra help.', 'My teacher who is very kind gave me extra help.'],
      1, 'Parenthesis with commas: a pair of commas wraps the extra information. Both needed! 👩‍🏫'),
    grmQ('Which is the SUBJUNCTIVE MOOD?',
      ['If I was you, I would study.', 'If I were you, I would study.', 'If I am you, I would study.', 'If I is you, I would study.'],
      1, '"If I were you" — the subjunctive uses "were" for ALL pronouns in formal/hypothetical clauses! 🎓'),
    grmQ('What is the effect of using a SHORT sentence after long ones?',
      ['It shows the writer has run out of ideas', 'It creates emphasis and impact', 'It is a grammar mistake', 'It makes the text too informal'],
      1, 'Short sentences create IMPACT. They stand out. They are powerful! ⚡'),
    grmQ('Which uses a COLON correctly to introduce a list?',
      ['She needed: pencil, ruler, and eraser.', 'She needed a pencil, ruler, and eraser.', 'She needed the following: a pencil, a ruler, and an eraser.', 'She needed — pencil, ruler, and eraser.'],
      2, '"She needed the following:" — the colon follows a complete clause, then introduces the list! ✏️'),
    grmQ('Which sentence uses a HYPHEN correctly?',
      ['A well known author visited our school.', 'A well-known author visited our school.', 'A well known-author visited our school.', 'A well known author, visited our school.'],
      1, 'Hyphens join compound adjectives before a noun: "well-known author". Without the noun, no hyphen needed! ✍️'),
    grmQ('Which is FORMAL language?',
      ['Kids should get more time off.', 'Students would benefit from additional recreational time.', 'We want more play time, yeah?', 'More play would be well good.'],
      1, 'Formal language: precise vocabulary, full sentences, no slang. For official writing! 🎩'),
    grmQ('Which sentence uses ELLIPSIS (...) correctly?',
      ['She opened the door...', 'She opened...the door...', '...opened she the door.', 'She opened the door.…'],
      0, 'Ellipsis creates tension or shows something is left unsaid. "She opened the door..." — what\'s next? 😮'),
    grmQ('What is a RELATIVE PRONOUN?',
      ['I, you, he, she', 'who, which, that, whose, whom', 'might, could, should', 'and, but, or'],
      1, 'Relative pronouns introduce relative clauses: who (people), which (things), that (either), whose (possession)! 🔗'),
    grmQ('Which correctly uses SEMI-COLONS in a complex list?',
      ['We visited Paris, France; Rome, Italy; and Berlin, Germany.', 'We visited Paris, France, Rome, Italy, and Berlin, Germany.', 'We visited Paris France; Rome Italy; Berlin Germany.', 'We visited: Paris, France; Rome, Italy; Berlin, Germany.'],
      0, 'Semi-colons separate items in a list when the items themselves contain commas! 🌍'),
    grmQ('Which sentence demonstrates PATHETIC FALLACY?',
      ['She was sad.', 'The dark clouds mirrored her gloomy mood.', 'It rained a lot.', 'She cried at the window.'],
      1, 'Pathetic fallacy uses weather/nature to reflect a character\'s emotions. Dark clouds = gloomy mood! 🌧️'),
    grmQ('Which modal verb shows POSSIBILITY (not certainty)?',
      ['will', 'must', 'shall', 'might'],
      3, '"Might" shows possibility — it may or may not happen. Will/shall = certainty, must = strong obligation! 🎲'),
    grmQ('What does the prefix "inter-" mean in "international"?',
      ['Inside', 'Against', 'Between or among', 'Before'],
      2, '"Inter-" means between or among: international (between nations), interact, interview! 🌐'),
  ];
}

// ── Year 6 (Age 10–11) ──────────────────────────────────────
function grmYear6() {
  return [
    grmQ('Which sentence is in the ACTIVE VOICE?',
      ['The trophy was won by the team.', 'The team won the trophy.', 'The trophy, won by the team, gleamed.', 'Won by the team, the trophy gleamed.'],
      1, 'Active voice: subject (team) performs the action. Passive reverses this. Active is usually more direct! 🏆'),
    grmQ('Which correctly uses a SEMICOLON to join clauses?',
      ['The sun set; the stars appeared.', 'The sun set, the stars appeared.', 'The sun set: the stars appeared.', 'The sun set. The stars appeared;'],
      0, 'A semicolon joins two closely related independent clauses — stronger than a comma, weaker than a full stop! ⭐'),
    grmQ('Which sentence uses the SUBJUNCTIVE correctly?',
      ['I suggest that he goes home now.', 'I suggest that he go home now.', 'I suggest that he went home now.', 'I suggest that he will go home now.'],
      1, '"He go" — the subjunctive uses the base form (no -s/es). Used in formal suggestions and "if" clauses! 🎓'),
    grmQ('What is the effect of ANAPHORA (repeating words at the start of clauses)?',
      ['It makes the text harder to read', 'It creates rhythm and emphasis', 'It is always a grammatical error', 'It makes the text shorter'],
      1, 'Anaphora: "We shall fight... We shall never surrender." Repetition creates power and rhythm! ✊'),
    grmQ('Which sentence uses a COLON correctly for an explanation?',
      ['She was exhausted: she had run a marathon.', 'She was exhausted, she had run a marathon.', 'She was exhausted; she had run a marathon.', 'She was exhausted — she had run.'],
      0, 'The colon says "here\'s why": She was exhausted: the reason follows. ✅🏃'),
    grmQ('Which is an example of a COMPOUND-COMPLEX sentence?',
      ['The dog barked.', 'The dog barked and ran away.', 'Although it was dark, the dog barked and ran.', 'The dog that barked.'],
      2, 'Compound-complex: two+ independent clauses + one subordinate clause. "Although it was dark" (sub) + "barked and ran" (compound)! 🐕'),
    grmQ('Which uses a DASH for dramatic effect?',
      ['She opened the box — it was empty.', 'She opened the box, it was empty.', 'She opened the box: it was empty.', 'She opened the box. it was empty.'],
      0, 'A dash creates a dramatic pause before a surprising or important reveal! 📦'),
    grmQ('Which sentence CORRECTLY converts to the PASSIVE?',
      ['Active: "The artist painted the mural." → Passive: "The mural was painted by the artist."', 'Active: "The artist painted the mural." → Passive: "The mural painted the artist."', 'Active: "The artist painted the mural." → Passive: "The artist was painted by the mural."', 'Active: "The artist painted." → Passive: "The mural was painted."'],
      0, 'Passive: object (mural) → subject, verb → "was/were + past participle", agent follows "by"! 🎨'),
    grmQ('What is a PARENTHETICAL PHRASE?',
      ['The main clause of a sentence', 'Extra information inserted into a sentence using brackets, dashes, or commas', 'A phrase at the start of a sentence', 'A type of subordinate clause'],
      1, 'Parenthetical phrase: extra info that can be removed — (like this) — without changing the meaning! 📝'),
    grmQ('Which demonstrates VARYING SENTENCE LENGTH for effect?',
      ['She walked. She talked. She laughed. She sang.', 'She walked and talked and laughed and sang happily.', 'The morning was bright and cheerful. She skipped. It was perfect.', 'She walked to school happily every single morning.'],
      2, 'Mix long (descriptive) and short (punchy) sentences for rhythm and emphasis. "She skipped." stands out! ✍️'),
    grmQ('Which sentence contains a NOUN CLAUSE?',
      ['The tall building collapsed.', 'That she had won was unbelievable.', 'Running fast, she won.', 'The prize, which was big, gleamed.'],
      1, '"That she had won" acts as the subject of the sentence — a noun clause functions like a noun! 🏅'),
    grmQ('Which is CORRECT use of "who" vs "whom"?',
      ['Who did you speak to?', 'To whom did you speak?', 'Whom spoke to you?', 'Whom are you?'],
      1, '"Whom" is the object form. "To whom did you speak?" (you spoke TO HIM → whom). 🗣️'),
    grmQ('What does the word "discourse marker" mean?',
      ['A punctuation mark', 'A word or phrase that links ideas or organises text', 'A type of verb', 'A prefix or suffix'],
      1, 'Discourse markers organise and link ideas: "However", "Furthermore", "In contrast", "As a result"! 🔗'),
    grmQ('Which is an example of IRONY?',
      ['The sun is hot.', '"What a lovely day," she said, standing in the pouring rain.', 'She was very happy.', 'The dog ran quickly.'],
      1, 'Irony: saying the OPPOSITE of what you mean. "What a lovely day" in the rain is ironic! 😏'),
    grmQ('Which correctly punctuates a SENTENCE CONTAINING PARENTHESIS and direct speech?',
      ['"Help!" she cried (her voice shaking).', '"Help!" she cried (Her voice shaking).', '"Help!" she cried, (her voice shaking).', '"Help" she cried (her voice shaking)!'],
      0, 'Direct speech + brackets: "Help!" (exclamation inside speech) then (extra detail) in brackets. ✅'),
  ];
}
