// Happy Games – Science Quiz Question Bank
// Topics: living things, materials, earth & space, forces, electricity, plants, animals, human body
'use strict';

const SCIENCE_QUESTIONS = {
  reception: [
    { q:"What do plants need to grow?", answers:["Sunlight and water","Only chocolate","Only TV","Just sand"], correct:0,
      explanation:"Plants need sunlight, water and soil to grow. They are living things just like us!" },
    { q:"How many seasons are there in a year?", answers:["Four","Two","Six","Three"], correct:0,
      explanation:"The four seasons are Spring, Summer, Autumn and Winter. Each season brings different weather." },
    { q:"Which animal lays eggs?", answers:["Hen","Dog","Horse","Cat"], correct:0,
      explanation:"Hens lay eggs! Birds, fish and many reptiles also lay eggs to have their babies." },
    { q:"Which of these is a living thing?", answers:["A tree","A rock","A car","A chair"], correct:0,
      explanation:"Trees are living — they grow, need food and water, and make new trees. Rocks, cars and chairs are not alive." },
    { q:"What comes out of clouds to water plants?", answers:["Rain","Jam","Fire","Sand"], correct:0,
      explanation:"Clouds are made of tiny water droplets. When they get heavy enough, rain falls down to the ground." },
    { q:"What do we use our eyes for?", answers:["Seeing","Hearing","Smelling","Tasting"], correct:0,
      explanation:"Our five senses are: sight (eyes), hearing (ears), smell (nose), taste (tongue) and touch (skin)." },
    { q:"Which season comes after Summer?", answers:["Autumn","Spring","Winter","Summer again"], correct:0,
      explanation:"The seasons go: Spring → Summer → Autumn → Winter → Spring again. Leaves fall in Autumn." },
    { q:"What do butterflies start life as?", answers:["Caterpillars","Fish","Tiny birds","Flowers"], correct:0,
      explanation:"Butterflies start as eggs, then hatch into caterpillars, form a chrysalis, then become butterflies! This amazing change is called metamorphosis." },
    { q:"What shape is the Earth?", answers:["Round like a ball","Flat","Square","Triangle"], correct:0,
      explanation:"The Earth is a sphere — a giant round ball. Astronauts can see this from space!" },
    { q:"Which animal lives in water and on land?", answers:["Frog","Lion","Elephant","Penguin"], correct:0,
      explanation:"Frogs live near ponds and can be in water AND on land. They start as tadpoles swimming in water, then grow legs!" }
  ],
  year1: [
    { q:"What do all animals need to survive?", answers:["Food, water and air","Just food","Just water","Only sunlight"], correct:0,
      explanation:"All animals (including humans!) need food for energy, water to stay hydrated, and air (oxygen) to breathe." },
    { q:"What is the Sun?", answers:["A star","A planet","A moon","A cloud"], correct:0,
      explanation:"The Sun is a huge star at the centre of our Solar System. It gives us the heat and light we need to live!" },
    { q:"What gives the Moon its light?", answers:["The Sun's light reflects off it","It makes its own light","Batteries inside it","Stars behind it"], correct:0,
      explanation:"The Moon doesn't make its own light — it reflects light from the Sun, like a giant mirror in space!" },
    { q:"What happens to ice when it warms up?", answers:["It melts into water","It gets harder","It flies away","It turns to fire"], correct:0,
      explanation:"Ice is frozen water. When it warms up it melts back into liquid water. Water can be solid (ice), liquid (water) or gas (steam)!" },
    { q:"What type of animal is a whale?", answers:["Mammal","Fish","Reptile","Bird"], correct:0,
      explanation:"Whales are mammals! They breathe air, are warm-blooded, and feed milk to their babies — just like dogs and cats." },
    { q:"How many legs does a spider have?", answers:["Eight","Six","Four","Ten"], correct:0,
      explanation:"Spiders have 8 legs — that's why they're arachnids, not insects! Insects (like ants and bees) have 6 legs." },
    { q:"What do we call animals that only eat plants?", answers:["Herbivores","Carnivores","Omnivores","Parasites"], correct:0,
      explanation:"Herbivores only eat plants (cows, rabbits). Carnivores eat meat (lions, sharks). Omnivores eat both (bears, humans)!" },
    { q:"Where does rain come from?", answers:["Water evaporates, rises and forms clouds","Only from mountains","It falls from the Moon","Trees make it"], correct:0,
      explanation:"The water cycle: water evaporates from oceans → rises as vapour → cools and forms clouds → falls as rain. It keeps repeating!" },
    { q:"Which part of a plant drinks up water from the soil?", answers:["Roots","Leaves","Flowers","Seeds"], correct:0,
      explanation:"Roots grow underground and soak up water and minerals from the soil. The water travels up the stem to reach the leaves." },
    { q:"What do we call animals that are active at night?", answers:["Nocturnal","Diurnal","Hibernating","Migratory"], correct:0,
      explanation:"Nocturnal animals (owls, bats, foxes) sleep in the day and are active at night. Diurnal animals are active during the day." }
  ],
  year2: [
    { q:"What is photosynthesis?", answers:["How plants make food using sunlight","How animals find food","How humans breathe","How water evaporates"], correct:0,
      explanation:"Photosynthesis is how plants make their own food! They use sunlight, water and CO₂ from the air to make glucose. As a bonus, they release oxygen for us to breathe!" },
    { q:"What gas do humans breathe in to survive?", answers:["Oxygen","Carbon dioxide","Nitrogen","Hydrogen"], correct:0,
      explanation:"We breathe IN oxygen and breathe OUT carbon dioxide. Plants do the opposite — they take in CO₂ and release oxygen. We need each other!" },
    { q:"What force pulls objects toward the ground?", answers:["Gravity","Magnetism","Friction","Electricity"], correct:0,
      explanation:"Gravity is the force pulling everything toward the centre of the Earth. It's why things fall down and why we stay on the ground!" },
    { q:"What are baby frogs called?", answers:["Tadpoles","Kittens","Larvae","Cubs"], correct:0,
      explanation:"Frogs lay eggs in water. They hatch into tadpoles (with tails!), then grow legs, and finally become frogs. This change is called metamorphosis!" },
    { q:"How many bones does an adult human body have?", answers:["206","100","350","500"], correct:0,
      explanation:"An adult human has 206 bones! Babies are born with about 270, which slowly join together as they grow." },
    { q:"Which organ pumps blood around the body?", answers:["Heart","Brain","Lungs","Liver"], correct:0,
      explanation:"Your heart is a powerful muscle that pumps blood through thousands of kilometres of blood vessels to every part of your body — every single second!" },
    { q:"What type of rock forms when lava from a volcano cools down?", answers:["Igneous rock","Sedimentary rock","Metamorphic rock","Crystal rock"], correct:0,
      explanation:"Igneous rock forms when hot molten rock (lava or magma) cools and hardens. The word 'igneous' comes from the Latin word for fire!" },
    { q:"What do we call animals that sleep through winter to save energy?", answers:["Hibernating","Migrating","Adapting","Camouflaging"], correct:0,
      explanation:"Hibernating animals (hedgehogs, bears, dormice) go into a very deep sleep through winter when food is scarce. Their heartbeat and breathing slow right down!" },
    { q:"What is the boiling point of water?", answers:["100°C","0°C","50°C","200°C"], correct:0,
      explanation:"Water boils and turns to steam at 100°C. It freezes into ice at 0°C. These temperatures are very useful reference points in science!" },
    { q:"What is wood made from?", answers:["Trees","Rocks","Animals","Water"], correct:0,
      explanation:"Wood is a natural material that comes from trees. It's used to build houses, make furniture, and paper! It's a renewable resource if trees are replanted." }
  ],
  year3: [
    { q:"What causes day and night?", answers:["Earth spinning on its axis","Earth moving away from the Sun","The Moon blocking sunlight","Clouds covering the Sun"], correct:0,
      explanation:"Earth spins (rotates) on its axis once every 24 hours. The side facing the Sun has day; the side facing away has night. One full spin = one day!" },
    { q:"What is friction?", answers:["A force that slows moving objects down","A type of electricity","A gas in the air","A part of the human ear"], correct:0,
      explanation:"Friction is the force that acts when two surfaces rub together. It slows things down! Rough surfaces have more friction than smooth ones. Bike brakes use friction!" },
    { q:"What are the three states of matter?", answers:["Solid, liquid and gas","Hot, cold and warm","Light, medium and dark","Metal, wood and plastic"], correct:0,
      explanation:"Everything is made of matter! Solid = fixed shape (ice). Liquid = flows (water). Gas = fills any container (steam). Matter can change between states with temperature." },
    { q:"What is a food chain?", answers:["Shows the order of who eats whom in nature","A chain made of metal food","How food is cooked in restaurants","How animals find water"], correct:0,
      explanation:"A food chain shows how energy passes through an ecosystem. Example: Grass → Rabbit → Fox. Plants are usually first (they're called 'producers')." },
    { q:"What does the Sun provide for life on Earth?", answers:["Light and heat energy","Sound energy","Electrical energy","Magnetic energy"], correct:0,
      explanation:"The Sun provides enormous amounts of light and heat energy. Without it, Earth would be frozen and dark — plants couldn't grow and nothing could survive!" },
    { q:"What do we call a planet's path around the Sun?", answers:["Orbit","Axis","Eclipse","Rotation"], correct:0,
      explanation:"A planet's orbit is its elliptical path around the Sun. Earth's orbit takes 365¼ days — which is why we have a leap year every 4 years!" },
    { q:"What is an invertebrate?", answers:["An animal with no backbone","An animal with a very long backbone","A plant without roots","A rock without crystals"], correct:0,
      explanation:"Invertebrates have no backbone. Worms, jellyfish, crabs, insects and spiders are all invertebrates. Vertebrates (fish, birds, mammals) DO have a backbone." },
    { q:"What is the water cycle?", answers:["Evaporation → clouds form → rain falls → rivers → ocean","Water going round in a circular pipe","Rain only","Snow melting only"], correct:0,
      explanation:"The water cycle never stops! Water evaporates from oceans → rises and forms clouds → falls as rain or snow → flows into rivers → back to the sea." },
    { q:"What is the closest star to our Solar System?", answers:["Proxima Centauri","Sirius","Betelgeuse","Polaris"], correct:0,
      explanation:"After our own Sun, Proxima Centauri is the nearest star — about 4.2 light-years away. Even travelling at the speed of light it would take over 4 years to reach it!" },
    { q:"Which gas do plants absorb from the air to make food?", answers:["Carbon dioxide","Oxygen","Nitrogen","Hydrogen"], correct:0,
      explanation:"Plants absorb carbon dioxide (CO₂) from the air and use it, along with water and sunlight, to make their food through photosynthesis." }
  ],
  year4: [
    { q:"What is an ecosystem?", answers:["All living things AND their non-living environment together","Only the plants in a forest","Only the animals in an area","Just the weather of a region"], correct:0,
      explanation:"An ecosystem includes ALL living things (plants, animals, bacteria) AND their non-living environment (air, water, soil, temperature). They all affect each other!" },
    { q:"What causes tides in the ocean?", answers:["The Moon's gravitational pull on Earth's water","Strong winds from mountains","The Earth spinning very fast","The Sun heating the sea"], correct:0,
      explanation:"The Moon's gravity pulls on Earth's oceans, creating bulges of water (high tides). As Earth rotates, different places experience high and low tides roughly twice a day." },
    { q:"What is DNA?", answers:["A molecule in cells that carries genetic information","A type of food nutrient","A kind of cloud formation","A special rock mineral"], correct:0,
      explanation:"DNA (deoxyribonucleic acid) is found in every cell of your body. It contains the instructions that determine how you look, grow and function — your body's instruction manual!" },
    { q:"What is electrical resistance?", answers:["How much a material opposes the flow of electric current","How electricity is stored","How electricity is created","How fast electricity moves"], correct:0,
      explanation:"Resistance is how much a material opposes electric current flowing through it. Good conductors (copper) have low resistance. Insulators (rubber) have very high resistance." },
    { q:"What are fossils?", answers:["Preserved remains of ancient organisms in rock","Rare precious gems","Bones of living animals","A type of colourful rock"], correct:0,
      explanation:"Fossils are preserved evidence of ancient life — bones, shells, teeth or even footprints — trapped in rock millions of years ago. They tell us the history of life on Earth!" },
    { q:"What is the role of decomposers in an ecosystem?", answers:["They break down dead matter and return nutrients to the soil","They produce food from sunlight","They hunt and eat other animals","They only produce oxygen"], correct:0,
      explanation:"Decomposers (bacteria and fungi) are nature's recyclers! They break down dead plants and animals, returning nutrients to the soil for new plants to grow. Without them, dead things would just pile up!" },
    { q:"What is static electricity?", answers:["A build-up of electric charge on a surface","Electricity from a wall socket","Electricity that moves through wires","Lightning that stays in clouds"], correct:0,
      explanation:"Static electricity builds up when certain materials rub together. You can create it by rubbing a balloon on your hair! The sudden release of static charge makes a spark — ZAP!" },
    { q:"What is the function of the lungs?", answers:["They exchange oxygen and carbon dioxide","They pump blood around the body","They digest food","They filter waste from the blood"], correct:0,
      explanation:"When you breathe in, lungs absorb oxygen into your blood. When you breathe out, they release carbon dioxide waste. Each lung contains millions of tiny air sacs (alveoli)!" },
    { q:"What is the difference between weathering and erosion?", answers:["Weathering breaks rock apart; erosion moves the pieces elsewhere","They mean exactly the same thing","Erosion is much slower than weathering","Weathering only happens to statues"], correct:0,
      explanation:"Weathering breaks rock into smaller pieces (rain, frost, wind). Erosion then MOVES those pieces to new places (rivers carry rock particles to the sea). Both shape our landscape!" },
    { q:"How do vaccines protect us from disease?", answers:["They train the immune system to recognise germs without causing illness","They kill all germs in your body instantly","They replace damaged cells with healthy ones","They make your body temperature too high for germs"], correct:0,
      explanation:"Vaccines introduce a safe version of a germ (dead or weakened) so your immune system learns to fight it. Then if the real germ ever arrives, your body is ready to defeat it quickly!" }
  ],
  year5: [
    { q:"What is natural selection?", answers:["Survival of organisms best suited to their environment, passing on useful traits","Humans choosing which animals survive in zoos","Plants choosing their own growing conditions","Animals randomly changing their appearance"], correct:0,
      explanation:"Charles Darwin's brilliant idea: organisms with helpful traits survive long enough to reproduce and pass those traits to offspring. Over many generations, the whole species adapts to its environment." },
    { q:"What are tectonic plates?", answers:["Giant pieces of Earth's crust that move very slowly","Layers of the ocean floor","A type of rock formation","Sections of the atmosphere"], correct:0,
      explanation:"Earth's crust is broken into about 15 major tectonic plates that move a few centimetres per year. When they collide or pull apart, they cause earthquakes, volcanoes and create mountains!" },
    { q:"What is a light-year?", answers:["The distance light travels in one year (~9.46 trillion km)","How long it takes light to reach us from the Sun","One year as experienced near a black hole","The brightness of a star per year"], correct:0,
      explanation:"A light-year is about 9.46 trillion kilometres — the distance light travels in one full year at 300,000 km per second! We use it to measure huge distances across the universe." },
    { q:"What is the greenhouse effect?", answers:["Certain gases in the atmosphere trap heat, keeping Earth warm","Plants in a greenhouse growing faster","The Sun gradually getting hotter over time","A layer of glass surrounding Earth"], correct:0,
      explanation:"The greenhouse effect is natural — gases like CO₂ and water vapour trap some of the Sun's heat, keeping Earth warm enough for life. But burning fossil fuels adds extra CO₂, causing too much warming." },
    { q:"What causes an earthquake?", answers:["Tectonic plates suddenly slipping against each other, releasing energy","Heavy rainfall deep underground","Very large animals moving through rock","Volcanic gases pushing through the ground"], correct:0,
      explanation:"Earthquakes happen at fault lines where tectonic plates meet. Stress builds up as plates try to move, then suddenly releases as an earthquake — sending shockwaves through the ground." },
    { q:"What is osmosis?", answers:["Water moving through a cell membrane from an area of more water to less water","Food breaking down inside a cell","Air entering through tiny pores in leaves","Salt dissolving in water"], correct:0,
      explanation:"Osmosis is how water naturally moves through cell membranes to balance concentration — from where there's MORE water to where there's LESS. It's vital for plants absorbing water from soil!" },
    { q:"What is a renewable energy source?", answers:["One that naturally replenishes (like solar, wind, tidal and hydro power)","Any energy source that never completely runs out","Oil and natural gas (they take so long to run out)","Nuclear power (uranium is very concentrated)"], correct:0,
      explanation:"Renewable energy comes from sources that naturally replenish on a human timescale: sun, wind, moving water, ocean tides. Fossil fuels are non-renewable — they take millions of years to form and are running out!" },
    { q:"What is the Milky Way?", answers:["The galaxy our Solar System lives in — about 200 billion stars","A type of nebula near our Solar System","Another name for our Solar System","The path the Moon takes across the sky"], correct:0,
      explanation:"The Milky Way is our home galaxy — a spiral-shaped collection of 200–400 billion stars (our Sun is just one of them!). It's about 100,000 light-years across. We live about halfway out from the centre." },
    { q:"What is the function of mitochondria in cells?", answers:["They produce energy (ATP) that powers the cell","They carry the cell's genetic information","They protect the cell from germs","They tell the cell what proteins to make"], correct:0,
      explanation:"Mitochondria are called the 'powerhouses of the cell'. They convert food (glucose) into ATP (adenosine triphosphate) — the universal energy currency that powers ALL cellular processes." },
    { q:"What is the difference between a chemical and a physical change?", answers:["Chemical = new substance formed; physical = just shape or state changes (reversible)","Chemical changes are always faster","Physical changes always need heat","There is no real difference"], correct:0,
      explanation:"Physical change: ice melting, paper tearing — no new substance, often reversible. Chemical change: burning, rusting, cooking — a new substance is created and it's usually irreversible!" }
  ],
  year6: [
    { q:"What is the difference between mitosis and meiosis?", answers:["Mitosis copies cells identically; meiosis creates sex cells with half the DNA","They are different names for the same process","Mitosis only happens in plants","Meiosis creates more cells and is faster"], correct:0,
      explanation:"Mitosis: one cell divides into two IDENTICAL copies (growth and repair). Meiosis: creates sperm or eggs with HALF the normal DNA — so when they join, the baby has the correct total amount." },
    { q:"What causes the seasons?", answers:["Earth's axis is tilted at 23.5° as it orbits the Sun","Earth moving closer to and then farther from the Sun","The Moon blocking different amounts of sunlight","Changes in the Sun's energy output through the year"], correct:0,
      explanation:"Earth's axis is tilted at 23.5°. As Earth orbits the Sun, the Northern Hemisphere tilts toward the Sun in summer (more direct sunlight, warmer) and away in winter (less direct, colder)." },
    { q:"What is the electromagnetic spectrum?", answers:["The full range of electromagnetic radiation ordered by wavelength","The range of colours visible to human eyes only","Sound waves of different frequencies","The range of gravitational forces"], correct:0,
      explanation:"The EM spectrum (from longest to shortest wavelength): radio waves → microwaves → infrared → visible light → ultraviolet → X-rays → gamma rays. We can only see the tiny visible light portion!" },
    { q:"What is the law of conservation of energy?", answers:["Energy cannot be created or destroyed — only transformed from one form to another","Energy always increases over time","Energy can disappear if used up completely","Heat is the original form of all energy"], correct:0,
      explanation:"One of the most important laws in physics! Energy is NEVER created from nothing or destroyed to nothing — it just changes form. Electrical → light and heat (in a bulb), chemical → kinetic (in muscles)." },
    { q:"What is evolution?", answers:["Species slowly change over many generations through natural selection","Individual animals change during their lifetime to survive","All life appeared suddenly all at once","Only plants evolve, animals do not"], correct:0,
      explanation:"Evolution explains the diversity of all life on Earth! Species gradually change over thousands of generations as favourable traits are passed on and less helpful ones disappear. Darwin described this as natural selection." },
    { q:"What is the Big Bang theory?", answers:["The universe began as an incredibly hot dense point about 13.8 billion years ago and has been expanding ever since","A huge explosion that occurred in the middle of existing space","The collision of two galaxies forming our universe","How stars form from clouds of gas"], correct:0,
      explanation:"The Big Bang is the leading scientific explanation for the origin of the universe. All matter, energy, space and time began from an unimaginably hot, dense singularity 13.8 billion years ago. The universe has been expanding ever since!" },
    { q:"What is CRISPR technology?", answers:["A precise gene-editing tool that can cut and modify DNA sequences","A type of virus that helps treat disease","A part of the human brain involved in memory","A chemical in plants used in medicine"], correct:0,
      explanation:"CRISPR-Cas9 is a revolutionary gene-editing technology (discovered in bacteria!). Scientists can use it to cut, remove or change specific DNA sequences — with potential to cure genetic diseases and transform medicine." },
    { q:"What is quantum mechanics?", answers:["Physics describing the behaviour of matter at the atomic and subatomic scale","The mechanics of very large objects in space","A type of advanced computer programming","The study of speed and acceleration only"], correct:0,
      explanation:"Quantum mechanics is the branch of physics governing subatomic particles (electrons, photons, quarks). At this tiny scale, particles behave in bizarre ways — they can exist in multiple states at once (superposition) until observed!" },
    { q:"What is bioluminescence?", answers:["Light produced chemically by living organisms (like fireflies and deep-sea fish)","Sunlight being absorbed and stored in living cells","Animals reflecting moonlight from their eyes","Light that makes plants glow when they photosynthesise"], correct:0,
      explanation:"Bioluminescence is nature's own glow-in-the-dark! Organisms like fireflies, some deep-sea fish, certain jellyfish, and some fungi produce light through a chemical reaction (luciferin + oxygen). It's used for attracting prey, finding mates, or warning predators!" },
    { q:"What is a half-life in radioactive decay?", answers:["The time it takes for half the radioactive atoms in a sample to decay","Half the total lifespan of a radioactive material","The time radiation is dangerous enough to harm humans","The rate at which energy is released per second"], correct:0,
      explanation:"Half-life is a fundamental property of radioactive elements. Carbon-14 has a half-life of 5,730 years — scientists use this to date ancient organic materials ('carbon dating'). Uranium-238's half-life is 4.5 BILLION years!" }
  ]
};
